apiVersion: v1
kind: Service
metadata:
  labels:
    app: ballerina-playground-webserver
  name: ballerina-playground-webserver-service
spec:
  ports:
    - name: "web-port-http"
      port: 80
      targetPort: 80  
  selector:
    app: ballerina-playground-webserver

